### ISSUE TITLE
Fix bug in delete function

### ISSUE THREAD

**Issue by ibraheem584** [ibraheem584/22F3648_22F3631#3]
The fix for the bug in the removeBook function enhances its clarity and functionality by ensuring it accurately reflects the operation's success. The method now includes comprehensive documentation that describes its purpose, parameters, and expected outcomes. By providing clear feedback to the user, it improves the user experience, allowing for easier debugging and better understanding of the library's operations. Overall, this fix ensures that the function behaves as intended, effectively managing the book removal process.

**Comment by makki-Q** [comment]
the issue has been resolved
